import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import AndamentoPedido from './andamentoPedido';
import Comanda from './comanda';
import Pedido from './pedido';
import PrePedido from './prePedido';
import Rascunho from './rascunho';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Creative Festa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Comanda />
        {/* <AndamentoPedido /> */}
        {/* <Rascunho /> */}
        {/* <PrePedido /> */}
        {/* <Pedido /> */}
      </main>
    </div>
  );
};

export default Home;
